### ISSUE TITLE
Failed to start remote client due to: dial tcp :9876: getsockopt: connection refused

### ISSUE THREAD

**Issue by shaharlinial** [topfreegames/apm#1]
So how to debug this?

Tried to run this:
`./apm bin apm --source="github.com/topfreegames/apm" --keep-alive`

**Comment by MateusDantas** [comment]
Did you try ro un ./apm serve before running ./apm bin?

**Comment by shaharlinial** [comment]
Hmm I tried now, but I can't really make it.
`FATA[0000] Failed to reborn daemon due to open /go/src/github.com/topfreemgames/apm/main.pid: no such file or directory. `

*I believe a clear example is needed*.
 I might write it for you the moment I figure out how to write that config file.

**Comment by MateusDantas** [comment]
Can you please describe me the exact steps you're running? Also I don't understand why you're trying to run APM which is a Process Manager with another APM instance.

**Comment by MateusDantas** [comment]
You don't need to write that config file. Just run ./apm serve and then ./apm bin and it should work fine. APM will create both the directory (which will be called '.apmenv' inside the folder you're running apm) and the config file for you.

**Comment by shaharlinial** [comment]
Ok I'm a bit confused.
I've written a http API in Go, and all I'm trying to do is to run it forever.. what exactly do I need to pass to ./apm serve?

**Comment by MateusDantas** [comment]
Nothing. Just run ./apm serve, then you can run you http api in go with './apm bin app-name --source="github.com/yourhttpapi/ingo".

**Comment by shaharlinial** [comment]
I guess I'm just retarded.. I can suggest writing an example to the Readme.md file
